/**
 * SPDX-FileComment: Markdown Report Generator
 * SPDX-FileType: SOURCE
 * SPDX-FileContributor: ZHENG Robert
 * SPDX-FileCopyrightText: 2026 ZHENG Robert
 * SPDX-License-Identifier: MIT
 *
 * @file markdown_generator.hpp
 * @brief Generates a tabular Markdown security report.
 * @version 1.0.0
 * @date 2026-04-06
 *
 * @author ZHENG Robert (robert@hase-zheng.net)
 * @copyright Copyright (c) 2026 ZHENG Robert
 *
 * @license MIT License
 */

#pragma once
#include "semver.hpp"
#include <fstream>
#include <iomanip>
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

namespace depdiscover {

using json = nlohmann::json;

/**
 * @brief Generates a tabular Markdown security report from internal JSON data.
 *
 * @param root The root of the internal JSON data.
 * @param filepath The path where the report will be saved.
 */
inline void generate_markdown_report(const json &root,
                                      const std::string &filepath) {
  std::ofstream out(filepath);
  if (!out) return;

  // Header Metadata
  if (root.contains("header")) {
    auto &h = root["header"];
    std::string proj = h.contains("project")
                           ? h["project"].value("name", "Unknown")
                           : "Unknown";
    std::string date = h.value("scan_date", "Unknown");
    out << "# SBOM Security Report: " << proj << "\n\n";
    out << "- **Scan Date:** " << date << "\n";
    out << "- **Generator Tool:** "
        << h["tool"]["name"].get<std::string>() << " v"
        << h["tool"]["version"].get<std::string>() << "\n\n";
  }

  // Table Header
  out << "| Package Name | Version | Fixed Version | Type | Licenses | Security Status |\n";
  out << "| :--- | :--- | :--- | :--- | :--- | :--- |\n";

  // Dependencies
  if (root.contains("dependencies")) {
    for (const auto &dep : root["dependencies"]) {
      std::string name = dep.value("name", "Unknown");
      std::string version = dep.value("version", "Unknown");
      std::string type = dep.value("type", "Unknown");

      // Format Licenses
      std::string licenses = "";
      if (dep.contains("licenses")) {
        for (const auto &lic : dep["licenses"]) {
          if (!licenses.empty()) licenses += ", ";
          licenses += lic.get<std::string>();
        }
      }
      if (licenses.empty()) licenses = "UNKNOWN";

      // Security Status & Highest Fixed Version
      int vuln_count = 0;
      std::string highest_fixed = "";
      std::string special_status = "";

      if (dep.contains("cves") && !dep["cves"].empty()) {
        for (const auto &cve : dep["cves"]) {
          std::string id = cve.value("id", "");
          if (id == "NOT-CHECKED") {
              special_status = "❓ UNKNOWN";
              continue;
          }
          if (id == "CHECK-ERROR") {
              special_status = "⚠️ ERROR";
              continue;
          }
          if (id == "SAFE") continue;

          vuln_count++;
          std::string fixed = cve.value("fixed_version", "");
          if (!fixed.empty()) {
            if (highest_fixed.empty() || compare_versions(fixed, highest_fixed) > 0) {
              highest_fixed = fixed;
            }
          }
        }
      }

      std::string status;
      if (!special_status.empty() && vuln_count == 0) {
        status = special_status;
      } else if (vuln_count == 0) {
        status = "✅ SAFE";
      } else {
        status = "❌ " + std::to_string(vuln_count) + " Vulnerabilities";
      }

      if (highest_fixed.empty()) highest_fixed = "-";

      out << "| " << name << " | " << version << " | " << highest_fixed << " | " 
          << type << " | " << licenses << " | " << status << " |\n";
    }
  }

  out << "\n---\n*Report generated by depdiscover*\n";
}

} // namespace depdiscover
